### ISSUE TITLE
[SR-14903] Crash while compiling swift on Debian

### ISSUE THREAD

**Issue by dhoepfl** [apple/swift#57250]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-14903      |
   |Radar             | rdar://problem/80384022         |
   |Original Reporter | @dhoepfl      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Swift source rev fca6072b931e4b5338b43472f5d18ccc59b99e17.

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 491b9a0f10363498805d545ee7c796f2

  </details>

**is blocked by**:  
* [SR-14978](https://bugs.swift.org/browse/SR-14978) Illegal instruction pshufb generated for old AMD CPU  

**Issue Description:**

``` java
/home/user/llvm/opt/usr/bin/swift-frontend -frontend -c -primary-file /home/user/llvm/swift-source/swift/benchmark/single-source/LuhnAlgoLazy.swift -emit-module-path /home/user/llvm/swift-source/build/buildbot_linux/benchmarks-linux-x86_64/Benchmark_Onone/x86_64-unknown-linux-gnu/debug/LuhnAlgoLazy.build/LuhnA
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the project and the crash backtrace.
Stack dump:
0.      Program arguments: /home/user/llvm/opt/usr/bin/swift-frontend -frontend -c -primary-file /home/user/llvm/swift-source/swift/benchmark/single-source/LuhnAlgoLazy.swift -emit-module-path /home/user/llvm/swift-source/build/buildbot_linux/benchmarks-linux-x86_64/Benchmark_Onone/x86_64-unknown-linux-gnu/deb
1.      Swift version 5.5-dev (LLVM 5e810bd6d7c2177, Swift fca6072b931e4b5)
2.      Compiling with effective version 4.1.50
3.      While evaluating request ParseSourceFileRequest(source_file "/home/user/llvm/swift-source/swift/benchmark/single-source/LuhnAlgoLazy.swift")
4.      With parser at source location: /home/user/llvm/swift-source/swift/benchmark/single-source/LuhnAlgoLazy.swift:121:7
 #&#8203;0 0x0000000005c761d3 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/user/llvm/opt/usr/bin/swift-frontend+0x5c761d3)
 #&#8203;1 0x0000000005c73fbe llvm::sys::RunSignalHandlers() (/home/user/llvm/opt/usr/bin/swift-frontend+0x5c73fbe)
 #&#8203;2 0x0000000005c7655c SignalHandler(int) (/home/user/llvm/opt/usr/bin/swift-frontend+0x5c7655c)
 #&#8203;3 0x00007fd00fe9b730 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x12730)
 #&#8203;4 0x0000000001b22c97 isValidIdentifierContinuationCodePoint(unsigned int) (/home/user/llvm/opt/usr/bin/swift-frontend+0x1b22c97)
 #&#8203;5 0x0000000001b1af43 swift::Lexer::lexTrivia(bool, char const*) (/home/user/llvm/opt/usr/bin/swift-frontend+0x1b1af43)
 #&#8203;6 0x0000000001b1a0c1 swift::Lexer::lexImpl() (/home/user/llvm/opt/usr/bin/swift-frontend+0x1b1a0c1)
 #&#8203;7 0x0000000001b75b8b swift::Parser::consumeTokenWithoutFeedingReceiver() (/home/user/llvm/opt/usr/bin/swift-frontend+0x1b75b8b)
 #&#8203;8 0x0000000001b24037 swift::Parser::isStartOfSwiftDecl() (/home/user/llvm/opt/usr/bin/swift-frontend+0x1b24037)
 #&#8203;9 0x0000000001b83b18 swift::Parser::parseBraceItems(llvm::SmallVectorImpl<swift::ASTNode>&, swift::BraceItemListKind, swift::BraceItemListKind, bool&) (/home/user/llvm/opt/usr/bin/swift-frontend+0x1b83b18)
#&#8203;10 0x0000000001b23537 swift::Parser::parseTopLevel(llvm::SmallVectorImpl<swift::Decl*>&) (/home/user/llvm/opt/usr/bin/swift-frontend+0x1b23537)
#&#8203;11 0x0000000001b80daa swift::ParseSourceFileRequest::evaluate(swift::Evaluator&, swift::SourceFile*) const (/home/user/llvm/opt/usr/bin/swift-frontend+0x1b80daa)
#&#8203;12 0x0000000001b8188c swift::SimpleRequest<swift::ParseSourceFileRequest, swift::SourceFileParsingResult (swift::SourceFile*), (swift::RequestFlags)12>::evaluateRequest(swift::ParseSourceFileRequest const&, swift::Evaluator&) (/home/user/llvm/opt/usr/bin/swift-frontend+0x1b8188c)
#&#8203;13 0x0000000001a57684 llvm::Expected<swift::ParseSourceFileRequest::OutputType> swift::Evaluator::getResultUncached<swift::ParseSourceFileRequest>(swift::ParseSourceFileRequest const&) (/home/user/llvm/optTraceback (most recent call last):
  File "/home/user/llvm/swift-source/swift/benchmark/scripts/build_script_helper.py", line 63, in <module>
    main()
  File "/home/user/llvm/swift-source/swift/benchmark/scripts/build_script_helper.py", line 57, in main
    perform_build(args, swiftbuild_path, "debug", "Benchmark_Onone", "-Onone")
  File "/home/user/llvm/swift-source/swift/benchmark/scripts/build_script_helper.py", line 39, in perform_build
    shutil.copy(binpath, finalpath)
  File "/usr/lib/python2.7/shutil.py", line 139, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/home/user/llvm/swift-source/build/buildbot_linux/benchmarks-linux-x86_64/Benchmark_Onone/debug/SwiftBench'
('-- Warning: {}', 'Host toolchain could not locate a compiler to build swift-driver. (Try `--skip-early-swift-driver`)')
--- Building cmark ---
```

The line in question is:

``` java
infix operator • : DotPrecedence
```

Hexdump:

    00000000  69 6e 66 69 78 20 6f 70  65 72 61 74 6f 72 20 e2  |infix operator .|
    00000010  80 a2 20 3a 20 44 6f 74  50 72 65 63 65 64 65 6e  |.. : DotPreceden|
    00000020  63 65 0a                                          |ce.|

**Comment by dhoepfl** [comment]
I think this was fixed in [LLVM](https://github.com/llvm/llvm-project/commit/6f1dbbc17c03206040eeaaee71e5db961f2cac30)
