### ISSUE TITLE
Error on `utils/update-checkout --clone-with-ssh` on RaspberryPi 64bit

### ISSUE THREAD

**Issue by TheBlckbird** [apple/swift#60527]
**Describe the bug**
I get this error when clonig all repos for contributing:
```
Cloning into 'llvm-project'...
Connection to github.com closed by remote host.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/pi/Desktop/swift-project/swift/utils/update_checkout/update_checkout/update_checkout.py", line 301, in obtain_additional_swift_sources
    shell.run(['git', 'clone', '--recursive', remote, repo_name] +
  File "/home/pi/Desktop/swift-project/swift/utils/swift_build_support/swift_build_support/shell.py", line 245, in run
    raise eout
Exception: ['git', 'clone', '--recursive', 'git@github.com:apple/llvm-project.git', 'llvm-project']
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/Desktop/swift-project/swift/utils/update-checkout", line 15, in <module>
    update_checkout.main()
  File "/home/pi/Desktop/swift-project/swift/utils/update_checkout/update_checkout/update_checkout.py", line 620, in main
    clone_results = obtain_all_additional_swift_sources(args, config,
  File "/home/pi/Desktop/swift-project/swift/utils/update_checkout/update_checkout/update_checkout.py", line 375, in obtain_all_additional_swift_sources
    return run_parallel(
  File "/home/pi/Desktop/swift-project/swift/utils/update_checkout/update_checkout/update_checkout.py", line 49, in run_parallel
    results = pool.map_async(func=fn, iterable=pool_args).get(999999)
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
Exception: ['git', 'clone', '--recursive', 'git@github.com:apple/llvm-project.git', 'llvm-project']
```

**Steps To Reproduce**
1. Clone the repo with `git clone git@github.com:apple/swift.git swift`
2. `cd swift`
3. `utils/update-checkout --clone-with-ssh`
   |_> it actually clones many of the other things, but crashes after when trying to clone llvm-project (the folder of it is empty):
![image](https://user-images.githubusercontent.com/66938161/184360230-66fd69a8-2c4b-4a55-a712-3914d4ee88a9.png)

**Expected behavior**
To finish cloning without crashing

**Screenshots**
look at above

**Environment (please fill out the following information)**
 - OS: RaspberryPi OS 64bit (modified Version of Debian)
 - Processor: Arm

**Additional context**
In the Getting started stand that you can use MacOS, Ubuntu...
Ubuntu is just a modified Version of Debian so why does it not work on RaspberryPi OS?

**Comment by 1Spinne** [comment]
Sorry for my bad English

**Comment by 1Spinne** [comment]
nvm i give up

**Comment by tbkka** [comment]
`llvm-project` is very large and so the `git` tool sometimes will time out trying to clone it.   I've been able to get it to work by running `utils/update-checkout --clone-with-ssh` again (you may need to delete the `llvm-project` folder first; I do not exactly remember how I fixed this last time).
