### ISSUE TITLE
Swift version 5.7.2 package is broken on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by pjmlp** [apple/swift#63036]
I just tried out the Swift 5.7.2 release package for Ubuntu 20.04 LTS and it seems to be missing some lldb stuff.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'lldb'
lldb version 13.0.0 (https://github.com/apple/llvm-project.git revision c41f13252ed4b49f246729b4d91ff521d5a6bf9d)
Swift version 5.7.2 (swift-5.7.2-RELEASE)
```

All the required dependencies for Ubuntu 20.04 LTS as per download instructions are installed.

So either the documentation is missing information for additional packages, or the tarball is missing contents.

**Comment by wti** [comment]
Same result for Swift 5.8.1.  Ubuntu 20.04 (LTS) has python 3.10, not 3.8.

(Should bug be renamed? e.g.,`In Swift on ubuntu 20.04, lldb expects python 3.8 instead of the available 3.10`?)

(1) lldb error when looking for libpython 3.8 (when 3.10 is installed):

`libpython3.8.so.1.0: cannot open shared object file: No such file or directory`

(2) apt-get reports python3.8 as likely obsoleted

(3) Using `ln` to alias 3.8 to 3.10 makes lldb library workable
albeit with module errors from CLI

Workaround from [vscode-swift 318](https://github.com/swift-server/vscode-swift/issues/318#issuecomment-1140400361)

```
export libRoot='/usr/lib/x86_64-linux-gnu/libpython'
sudo ln -s "${libRoot}3.10.so.1.0" "${libRoot}3.8.so.1.0"
```

After `ln`, errors do show in CLI:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'lldb'
lldb version 13.0.0git (https://github.com/apple/llvm-project.git revision f0fb631dd1a3a2988b23ba5057cd9106713cd0b4)
Swift version 5.8.1 (swift-5.8.1-RELEASE)
```

But with this workaround VSCode is able to use lldb (via library?), albeit likely with bugs.

See also [swift 60255 comment ](https://github.com/apple/swift/issues/60255#issuecomment-1263312839)

**Comment by MahdiBM** [comment]
I think this issue should be resolved in the latest toolchains (I think It's related to addition of installation of `python3-lldb-13` or another python lib into the toolchains and Dockerfiles and all).
