### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 20905: invalid start byte

### ISSUE THREAD

**Issue by lyj102012** [apple/swift#66755]
**Description**
when i build swift toolchain, I get this error and i don't know what should I do

**Steps to reproduce**

I execute the following command：
git clone https://github.com/apple/swift.git
cd swift
utils/update-checkout --clone
./swift/utils/build-toolchain com.xxxx --sccache

**Expected behavior**

I want to compile swift toolchain successfully, but keep getting errors.
What should I do?
**Environment**
- Swift compiler version info: master feature
- Xcode version info : 14.3.1
- Deployment target: 
cmake version 3.26.0
sccache 0.5.3
ninja 1.12.0.git
Python 3.11.4

**Comment by lyj102012** [comment]
Traceback (most recent call last):
  File "/Users/xxx/Desktop/swift-project/swift-driver/Utilities/build-script-helper.py", line 706, in <module>
    main()
  File "/Users/xxx/Desktop/swift-project/swift-driver/Utilities/build-script-helper.py", line 703, in main
    handle_invocation(args)
  File "/Users/xxx/Desktop/swift-project/swift-driver/Utilities/build-script-helper.py", line 185, in handle_invocation
    build_using_cmake(args, toolchain_bin, args.build_path, targets)
  File "/Users/xxx/Desktop/swift-project/swift-driver/Utilities/build-script-helper.py", line 443, in build_using_cmake
    build_llbuild_using_cmake(args, target, swiftc_exec, dependencies_dir,
  File "/Users/xxx/Desktop/swift-project/swift-driver/Utilities/build-script-helper.py", line 485, in build_llbuild_using_cmake
    cmake_build(args, swiftc_exec, llbuild_cmake_flags, llbuild_swift_flags,
  File "/Users/xxx/Desktop/swift-project/swift-driver/Utilities/build-script-helper.py", line 590, in cmake_build
    stdout, stderr = ninjaProcess.communicate()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1209, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 2146, in _communicate
    stdout = self._translate_newlines(stdout,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1086, in _translate_newlines
    data = data.decode(encoding, errors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 20905: invalid start byte
