### ISSUE TITLE
swift-llbuild Windows CI fails to start

### ISSUE THREAD

**Issue by owenv** [apple/swift#69685]
Example: https://ci-external.swift.org/job/swift-llbuild-PR-windows/74/console

multiple retries show the exact same failure, just after git checkouts:

```
[swift-llbuild-PR-windows] $ cmd /c call /tmp/jenkins4304545878376433073.bat
FATAL: command execution failed
java.io.IOException: error=2, No such file or directory
	at java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to ubuntu-16.04-android
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1797)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:1001)
		at hudson.Launcher$RemoteLauncher.launch(Launcher.java:1122)
		at hudson.Launcher$ProcStarter.start(Launcher.java:507)
		at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:143)
		at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:91)
		at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
		at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:806)
		at hudson.model.Build$BuildExecution.build(Build.java:198)
		at hudson.model.Build$BuildExecution.doRun(Build.java:163)
		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:514)
		at hudson.model.Run.execute(Run.java:1888)
		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
		at hudson.model.ResourceController.execute(ResourceController.java:99)
		at hudson.model.Executor.run(Executor.java:432)
Caused: java.io.IOException: Cannot run program "cmd" (in directory "/home/ubuntu/jenkins/workspace/swift-llbuild-PR-windows"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at hudson.Proc$LocalProc.<init>(Proc.java:252)
	at hudson.Proc$LocalProc.<init>(Proc.java:221)
	at hudson.Launcher$LocalLauncher.launch(Launcher.java:995)
	at hudson.Launcher$ProcStarter.start(Launcher.java:507)
	at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:1393)
	at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:1335)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:376)
	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:829)
Build step 'Execute Windows batch command' marked build as failure
Adding one-line test results to commit status...
Setting status of 2bbb1ac512de5045ff9477440a55102edb24b4be to FAILURE with url https://ci-external.swift.org/job/swift-llbuild-PR-windows/74/ and message: 'Build finished. No test results found.'
Using context: Swift Test Windows Platform
Finished: FAILURE
```

This looks different from some of the earlier issues.

cc @shahmishal

**Comment by shahmishal** [comment]
It was picking up the wrong node, it's now resolved.

**Comment by owenv** [comment]
thanks!
